server:
  compression:
    enabled: true
    mime-types: application/json
  port: ${APPLICATION_PORT:8080}
spring:
  application:
    name: Social media wall
  #profiles:
    #active: local-mongodb
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:smwall-database}
      username: ${DB_USER_NAME:root}
      password: ${DB_USER_PASSWORD:root}

  flyway:
    baseline-on-migrate: true
    enabled: false
    baseline-version: 0.1.0
    table: sm_wall
    locations: classpath:migration
  h2:
    console:
      enabled: false
  cloud:
    openfeign:
      client:
        config:
          meta:
            default-request-headers:
              Authorization: ${AUTHORIZATION_KEY}


application:
  webhooks:
    meta:
      hashtags:
        - devoxxma_smw1: ${HASHTAG1_ID}
        - devoxxma_smw1: ${HASHTAG2_ID}
      user-id:  ${USER_ID}
      app-secret: ${APP_SECRET}
      schedule:
        hashtag-delay: 60000
        tag-delay: 60000
        user-media-delay : 5000
        story-delay : 60000

