server:
  compression:
    enabled: true
    mime-types: application/json
  port: ${APPLICATION_PORT:8080}
spring:
  application:
    name: Social media wall
  #profiles:
    #active: local-mongodb
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:smwall-database}
      username: ${DB_USER_NAME:root}
      password: ${DB_USER_PASSWORD:root}

  flyway:
    baseline-on-migrate: true
    enabled: false
    baseline-version: 0.1.0
    table: sm_wall
    locations: classpath:migration
  h2:
    console:
      enabled: false
  cloud:
    openfeign:
      client:
        config:
          meta:
            default-request-headers:
              Authorization: Bearer EAARpf12qyg8BAJieqDp4ZB6GDPZCKAexsVc8ZCIIZBs2T0djhD3F4VFfN3RzzSKmLcjfzMQ0bQsO6OF6CtwP6t4J4reUGNfLFsMFT2iEY1OEXhUN2fQNUaXHEZB4ZC9WxI74ZCE0oz7CWdZBYmGCK3FfLRB1rZAjHTfLA0sOiZBFws36FOQYR02pZBn3vNEqLP7Do4ZD


application:
  webhooks:
    meta:
      hashtags:
        - devoxxma_smw1: 18280910683186124
        - devoxxma_smw1: 17979847571109666
      userId: 17841458686619394
      app-secret: d305deab8e8e7c27802c6bb1fb7b3a72
      schedule:
        hashtag-delay: 60000
        tag-delay: 60000
        user-media-delay : 5000
        story-delay : 60000