server:
  port: ${APPLICATION_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: Social media wall
  profiles:
    group:
      dev:
        - dev
        - yt
        - meta
  data:
    mongodb:
      authentication-database: admin
      port: ${DB_PORT:27017}
      uri: mongodb+srv://root:42SeecaPiOWkXGU0@cluster0.7bkt6ir.mongodb.net/?retryWrites=true&w=majority
      database: SM_wall
  flyway:
    baseline-on-migrate: true
    enabled: false
    baseline-version: 0.1.0
    table: sm_wall
    locations: classpath:migration
  h2:
    console:
      enabled: false
  cloud:
    openfeign:
      oauth2:
        enabled: true
      client:
        config:
          meta:
            default-request-headers:
              Authorization: ${AUTHORIZATION_KEY}
  task:
    execution:
      thread-name-prefix: smwall-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: smwall-scheduling-
      pool:
        size: 2
  servlet:
    multipart:
      max-file-size: 2MB
      enabled: true
  email:
   username: ${USERNAME}
   password: ${PASSWORD}
   link-dev: ${LINK-DEV}
   smtp:
      auth : true
      host: ${HOST}
      port: ${PORT}
      starttlsEnable: true
      sslProtocols: ${SSL-PROTOCOLS}

application:
  cache:
    ehcache:
      time-to-live: 86400
      max-entries: 1000
  security:
    auth:
      jwt:
        base64-secret: N2VlNDE1MThhZjVjM2VlNDZlMDIxMjM4MjM5MTJkOWM4OWI1NjQzNzNhZTZlMWJiY2ZmZjc1OTFmNWVhNjczOTNmNjA4ZjBkOGNkZTI3NWNlODBkYTlkZTVmZWE1ZDc0OGJiNmEwNGI5ODI4OWY0OWFiYTE2MTc4NjEzMjZjMjM=
        # Token validity in seconds
        token-validity: 2592000
  webhooks:
    meta:
      verify-token: ${META_SUBSCRIPTION_VERIFY_TOKEN}
      resource-id-prefix: MT-
      hashtags:
        - devoxxma_smw1: ${HASHTAG1_ID}
        - devoxxma_smw2: ${HASHTAG2_ID}
      user-id: ${USER_ID}
      username: ${USERNAME}
      app-secret: ${APP_SECRET}
      scheduling:
        # Task scheduling intervals in `seconds`
        hashtag-media-interval: 36
        user-tags-interval: 72
        user-stories-interval: 106
        user-media-interval: 225
    youtube:
      verify-token: ${YOUTUBE_SUBSCRIPTION_VERIFY_TOKEN}
      resource-id-prefix: YT-
      scheduling:
        # Task scheduling intervals in `seconds`
        shorts-delay: 2160
        video-delay: 2160
        channel-video-delay: 4320
      api-key: ${API_KEY}
      channel-id: ${CHANNEL_ID}
      keyword: ${KEYWORD}
      safeSearch: strict

  text-filter:
    perspective-api:
      apiKey: ${API_KEY}
  media-filter:
    urlScriptImage: src/main/resources/filterImages.py
    urlScriptVideo: src/main/resources/filterVideos.py

app:
  url: FRONT_END_URL
