server:
  compression:
    enabled: true
    mime-types: application/json
  port: ${APPLICATION_PORT:8080}
spring:
  application:
    name: Social media wall
  profiles:
    active: local-mongodb
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
      username: ${DB_USER_NAME}
      password: ${DB_USER_PASSWORD}
  flyway:
    baseline-on-migrate: true
    enabled: false
    baseline-version: 0.1.0
    table: sm_wall
    locations: classpath:migration
  h2:
    console:
      enabled: false


