server:
  port: ${APPLICATION_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: Social media wall
  #profiles:
    #active: local-mongodb
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:smwall-database}
      username: ${DB_USER_NAME:root}
      password: ${DB_USER_PASSWORD:root}
  flyway:
    baseline-on-migrate: true
    enabled: false
    baseline-version: 0.1.0
    table: sm_wall
    locations: classpath:migration
  h2:
    console:
      enabled: false
  cloud:
    openfeign:
      oauth2:
        enabled: true
      client:
        config:
          meta:
            default-request-headers:
              Authorization: ${AUTHORIZATION_KEY}
  task:
    execution:
      thread-name-prefix: smwall-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: smwall-scheduling-
      pool:
        size: 2

application:
  cache:
    ehcache:
      time-to-live: 86400
      max-entries: 1000
  webhooks:
    meta:
      hashtags:
        - devoxxma_smw1: ${HASHTAG1_ID}
        - devoxxma_smw2: ${HASHTAG2_ID}
      user-id: ${USER_ID}
      app-secret: ${APP_SECRET}
      scheduling:
        # Task scheduling intervals in `seconds`
        hashtag-media-interval: 100
        user-tags-interval: 100
        user-stories-interval: 100
        user-media-interval: 100
    youtube:
      scheduling:
        shorts-delay: 900 #15min
      api-key:
      channel-id:

app:
  url: ${FRONT_END_URL}
